version: '3'

services:
  api:
    build: .
    command: bash -c "make test"
    depends_on:
      - db
    environment:
      PORT: '8080'

  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: password
